/aruco_node:
  ros__parameters:
    marker_size: 0.065
    aruco_dictionary_id: DICT_5X5_100

    #original camera topics
    #image_topic: /camera/image_raw
    #camera_info_topic: /camera/camera_info

    #using gazebo simulation camera topics
    # image_topic: /realsense/color/image_raw
    # camera_info_topic: /realsense/color/camera_info

    #using hardware realsense camera topics
    image_topic: /camera/color/image_raw
    camera_info_topic: /camera/color/camera_info
