aruco_node:
  ros__parameters:
    marker_size: 0.07
    aruco_dictionary_id: DICT_5X5_100

    # original camera topics
    # image_topic: /camera/image_raw
    # camera_info_topic: /camera/camera_info

    # using gazebo simulation camera topics
    # image_topic: /realsense/color/image_raw
    # camera_info_topic: /realsense/color/camera_info

    # using hardware realsense camera topics
    image_topic: /camera/color/image_raw
    camera_info_topic: /camera/color/camera_info

    # Lab parameters
    robot_center_offset: [0.084, -0.084, 0.0, 1.0]   # in metres
    gTc_matrix: [
      1.0, 0.0, 0.0, 1.3, 
      0.0, -1.0, 0.0, 0.98, 
      0.0, 0.0, -1.0, 2.67, 
      0.0, 0.0, 0.0, 1.0
      ]
